name: Handle Sentry Releases
author: andre
description: Creates and finalize a specific application version at Sentry

inputs:
  action:
    description: "Action to perform at Sentry [create/finalize]"
    required: true

  version:
    description: "Version to perform action"
    required: true

  sentry_auth_token:
    description: "Sentry authentication token"
    required: true

  sentry_project:
    description: "Sentry Project ID"
    required: true

  sentry_org:
    description: "Sentry Organization"
    required: true

runs:
  using: composite
  steps:
    - name: ${{ inputs.action }} Sentry release
      shell: bash
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry_auth_token }}
      run: |      
        echo "Creating release ${{ inputs.version }}"
        npx sentry-cli releases ${{ inputs.action }} \
        --org ${{ inputs.sentry_org }} \
        --project ${{ inputs.sentry_project }} \
        "${{ inputs.version }}"

